name: Java CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [reopened, opened, synchronize]
  schedule:
    - cron:  '30 5 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-14]
        java: [8, 11, 17]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Test with Maven
        run: ./mvnw test -B -V -D"java.util.logging.config.file"="logging.properties" -D"http.keepAlive"="false" -D"maven.wagon.http.pool"="false" -D"maven.wagon.httpconnectionManager.ttlSeconds"="120"

  test-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        java: [8, 11, 17]
      fail-fast: false
      max-parallel: 3
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Test with Maven on Windows
        run: ./mvnw.cmd test -B -V -D"java.util.logging.config.file"="logging.properties" -D"http.keepAlive"="false" -D"maven.wagon.http.pool"="false" -D"maven.wagon.httpconnectionManager.ttlSeconds"="120"
